apiVersion: apps/v1
kind: Deployment
metadata:
  name: udehiggjsguj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udehiggjsguj
  template:
    metadata:
      labels:
        app: udehiggjsguj
    spec:
      containers:
      - image: okteto.dev/udehiggjsguj:latest
        name: udehiggjsguj
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e452d122-bafd-4d84-a37a-879dbcef60c7"
        - name: Vless_Path
          value: "/879dbcef60c7vless"
        - name: Vmess_UUID
          value: "e452d122-bafd-4d84-a37a-879dbcef60c7"
        - name: Vmess_Path
          value: "/879dbcef60c7vmess"
        - name: Share_Path
          value: "/v2link"
